apiVersion: v1
kind: Service
metadata:
  name: guestbook-vassaln
  labels:
    app: guestbook-vassaln
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    name: http
  selector:
    app: guestbook-vassaln
