name: 'Push images'
on:
  push:
    branches:
      - main

  workflow_dispatch:

defaults:
  run:
    working-directory: ./guestbook

jobs:
  push_to_registry:
    name: Buildpush
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag nicolasvassal/guestbook:$GITHUB_SHA

      - name: Push Docker image
        run: docker push nicolasvassal/guestbook:$GITHUB_SHA
